SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = ../src/cpu.sv ../src/fetch.sv ../src/decode.sv ../src/execute.sv ../src/regfile.sv
TOPLEVEL = cpu
MODULE = cpu_test
include $(shell cocotb-config --makefiles)/Makefile.sim
