SIM ?= verilator
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../src/mxu_controller.sv
TOPLEVEL = mxu_controller
MODULE = test_mxu_controller
VERILATOR_TRACE = 1
include $(shell cocotb-config --makefiles)/Makefile.sim