SIM ?= verilator
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../src/accum_bank.sv
TOPLEVEL = accum_bank
MODULE = test_accum_bank
VERILATOR_TRACE = 1
include $(shell cocotb-config --makefiles)/Makefile.sim