SIM ?= verilator
TOPLEVEL_LANG = verilog
VERILATOR_TRACE = 1
VERILOG_SOURCES = $(PWD)/../../pe/pe.sv $(PWD)/../systolic_array.sv
TOPLEVEL = systolic_array
MODULE = systolic_array_test
include $(shell cocotb-config --makefiles)/Makefile.sim