SIM ?= icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../../pe/src/pe.sv $(PWD)/../src/systolic_array.sv
TOPLEVEL = systolic_array
MODULE = systolic_array_test
include $(shell cocotb-config --makefiles)/Makefile.sim