SIM ?= verilator
TOPLEVEL_LANG = verilog
VERILATOR_TRACE = 1
VERILOG_SOURCES = $(PWD)/../src/deskew_buffer.sv
TOPLEVEL = deskew_buffer
MODULE = test_deskew_buffer
include $(shell cocotb-config --makefiles)/Makefile.sim