# rtl/skew_buffer/sim/Makefile
SIM ?= icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../src/deskew_buffer.sv
TOPLEVEL = deskew_buffer
MODULE = test_deskew_buffer
include $(shell cocotb-config --makefiles)/Makefile.sim