SIM ?= verilator
TOPLEVEL_LANG = verilog
VERILATOR_TRACE = 1
VERILOG_SOURCES = $(PWD)/../src/skew_buffer.sv
TOPLEVEL = skew_buffer
MODULE = test_skew_buffer
include $(shell cocotb-config --makefiles)/Makefile.sim