# rtl/skew_buffer/sim/Makefile
SIM ?= icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../src/skew_buffer.sv
TOPLEVEL = skew_buffer
MODULE = test_skew_buffer
include $(shell cocotb-config --makefiles)/Makefile.sim